train:
	python3 model/train_model.py

install:
	pip install -r requirements.txt

run:
	python3 app.py

clean:
	rm -f model/phishing_model.pkl

check-model:
	test -f model/phishing_model.pkl && echo "Modelo entrenado encontrado." || echo "El modelo no existe. Ejecuta 'make train'"

all: install train run
